const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const cache = new Map();
function load(name) {
 if (cache.has(name)) return cache.get(name);
 const file = path.resolve(__dirname, '../src/data', name + '.ts');
 const mod = new Module(file, module);
 mod.filename = file;
 mod.paths = module.paths;
 mod.require = ref => ref === './constants' ? load('constants') : require(ref);
 mod._compile(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, file);
 cache.set(name, mod.exports);
 return mod.exports;
}
const { normalizeCharacter, level, pool, updateAbility } = load('character');
const base = normalizeCharacter({ name: '测试调查员', sanity: 4, stability: 1, health: 1, skills: { '运动': '8' }, equipmentItems: [] });
assert.equal(level(base, '心智(9)'), 4);
let character = updateAbility(base, '健康(9)', 9, false);
assert.equal(character.health, 9);
assert.equal(character.skills['健康(9)'], '9');
character = updateAbility(character, '健康(9)', -3, true);
assert.equal(pool(character, '健康(9)'), -3);
assert.equal(level(character, '健康(9)'), 9);
character = updateAbility(character, '运动', 5, true);
assert.equal(pool(character, '运动'), 5);
assert.equal(level(character, '运动'), 8);
assert.equal(pool(updateAbility(character, '运动', 20, true), '运动'), 8);
assert.equal(level(updateAbility(base, '运动', -2, false), '运动'), 0);
assert.equal(level(updateAbility(base, '运动', 10000, false), '运动'), 99);
const restored = normalizeCharacter(JSON.parse(JSON.stringify(character)));
assert.equal(pool(restored, '健康(9)'), -3);
assert.equal(pool(restored, '运动'), 5);
assert.equal(pool({ ...restored, pools: {} }, '运动'), 8);
assert.equal(normalizeCharacter({ ...base, skills: { '健康(9)': '7' }, health: 2 }).health, 7);
assert.throws(() => normalizeCharacter({ ...base, pools: { '运动': '坏数据' } }));
assert.throws(() => normalizeCharacter({ ...base, equipmentItems: [null] }));
console.log('通过：状态同步、等级与池分离、消耗与恢复、边界输入、旧存档迁移及存档往返。');
